Pkg.Desc=Android SDK Platform 17
Pkg.UserSrc=false
Platform.Version=17
Platform.CodeName=
Pkg.Revision=2
AndroidVersion.ApiLevel=37.0
AndroidVersion.CodeName=
AndroidVersion.ExtensionLevel=22
AndroidVersion.IsBaseSdk=true
AndroidVersion.PreviewSdkInt=0
AndroidVersion.BetaVersion=
Layoutlib.Api=15
Layoutlib.Revision=1
Platform.MinToolsRev=22
